apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
    - host: stickatag.com
      http:
        paths:
          - path: /api/user/?(.*)
            backend:
              serviceName: authentication-service
              servicePort: 3000
          - path: /api/product/?(.*)
            backend:
              serviceName: product-service
              servicePort: 3000
          - path: /api/category/?(.*)
            backend:
              serviceName: product-service
              servicePort: 3000