apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: rayanma/product
        env:
          - name: MONGO_URI
            value: "mongodb://product-mongo-service:27017/products"
          - name: NATS_CLUSTER_ID
            value: "mainstreet"
          - name: NATS_URL
            value: "http://nats-service:4222"
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product
  ports:
  - name: product
    protocol: TCP
    port: 3000
    targetPort: 3000