apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: rayanma/product
        env:
          - name: MONGO_URI
            value: "mongodb://product-mongo-service:27017/product"
          - name: AWS_S3_PRODUCT_PHOTOS_BUCKET
            valueFrom:
              secretKeyRef:
                name: aws-s3-product-photos-bucket
                key: AWS_S3_PRODUCT_PHOTOS_BUCKET
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret-access-key
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-access-key-id
                key: AWS_ACCESS_KEY_ID
          - name: NATS_URL
            value: "http://nats-service:4222"
          - name: NATS_CLUSTER_ID
            value: "mainstreet"
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product
  ports:
  - name: product
    protocol: TCP
    port: 3000
    targetPort: 3000