name: tests-authentication
on:
  pull_request:
    paths:
      - "services/authentication/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd services/authentication && npm install && npm run test:ci